apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx-svc
  name: nginx-svc
spec:
  ports:
    - name: nginx
      port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    app: nginx
  type: ClusterIP
status:
  loadBalancer: {}
