global:
  smtp_smarthost: "smtp.gmail.com:587"
  smtp_from: "alertmanager@gmail.com"
  smtp_auth_username: "thainguyen.uet@gmail.com"
  smtp_auth_password: "your_app_password"

route:
  receiver: "email-notifications"
  routes:
    - match:
        severity: critical
      receiver: "email-notifications"

receivers:
  - name: "email-notifications"
    email_configs:
      - to: "thainguyen.uet@gmail.com"

inhibit_rules:
  - source_match:
      severity: "critical"
    target_match:
      severity: "warning"
    equal: ["alertname", "dev", "instance"]
